server {

    server_name speak-shine.sidhartht.online;

    location / {

        proxy_pass http://app:3001;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_cache_bypass $http_upgrade;

        client_max_body_size 120m;

        proxy_read_timeout 300s;

        proxy_send_timeout 300s;
    }

    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/speak-shine.sidhartht.online/fullchain.pem;

    ssl_certificate_key /etc/letsencrypt/live/speak-shine.sidhartht.online/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;

    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}


server {

    listen 80;

    server_name speak-shine.sidhartht.online;

    return 301 https://$host$request_uri;
}