name: Speak-Shine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true

          script: |
            cd ~/Speak-Shine

            echo "Pull latest code"

            git pull origin main

            echo "Install packages"

            npm install

            echo "Restart PM2"

            pm2 restart speak-shine

            echo "Deployment success"