name: Speak-Shine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with Docker Compose Rollback
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/Speak-Shine-

            echo "================================="
            echo "Pull latest code"
            echo "================================="

            git pull origin main

            echo "================================="
            echo "Creating backup compose file"
            echo "================================="

            cp docker-compose.yml docker-compose.backup.yml

            echo "================================="
            echo "Stopping old containers"
            echo "================================="

            docker compose down

            echo "================================="
            echo "Cleaning unused Docker resources"
            echo "================================="

            docker system prune -f

            echo "================================="
            echo "Starting updated containers"
            echo "================================="

            docker compose up -d --build

            echo "================================="
            echo "Waiting for health check"
            echo "================================="

            sleep 20

            echo "================================="
            echo "Checking container health"
            echo "================================="

            if docker ps | grep speak-shine-app; then

              echo "================================="
              echo "Deployment successful"
              echo "================================="

            else

              echo "================================="
              echo "Deployment failed"
              echo "Rolling back..."
              echo "================================="

              docker compose down

              cp docker-compose.backup.yml docker-compose.yml

              docker compose up -d --build

              exit 1

            fi

            echo "================================="
            echo "Running containers"
            echo "================================="

            docker ps

            echo "================================="
            echo "Deployment completed"
            echo "================================="

            

# name: Speak-Shine Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to AWS EC2
#         uses: appleboy/ssh-action@master

#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_KEY }}

#           script: |
#             cd ~/Speak-Shine-

#             git pull origin main

#             npm install

#             pm2 restart speak-shine